# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=6
inherit gnome2 meson multilib-minimal

DESCRIPTION="GTK+ & GNOME Accessibility Toolkit"
HOMEPAGE="https://wiki.gnome.org/Accessibility"

LICENSE="LGPL-2+"
SLOT="0"
KEYWORDS="~amd64"
IUSE="+introspection nls test"

RDEPEND="
	>=dev-libs/glib-2.31.2:2[${MULTILIB_USEDEP}]
	introspection? ( >=dev-libs/gobject-introspection-0.6.7:= )
"
DEPEND="${RDEPEND}
	>=dev-lang/perl-5
	dev-util/gtk-doc-am
	>=virtual/pkgconfig-0-r1[${MULTILIB_USEDEP}]
	nls? ( >=sys-devel/gettext-0.19.2 )
"

multilib_src_configure() {
	local emesonargs=(
		-Dintrospection=$(multilib_native_usex introspection true false)
	)

	meson_src_configure
}

multilib_src_compile() { meson_src_compile; }

multilib_src_install() {
	meson_src_install

	# This autogenerated header includes multilib-specific full paths
	# from build which break the multilib header comparison, so remove
	# the multilib-specific base part of the path from the comments.
	sed -e 's:enumerations from "[^"]*\.\./[^/]*/:enumerations from ":' \
	    -i "${D}/usr/include/atk-1.0/atk/atk-enum-types.h"
}
