# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.14.0

EAPI=8

CRATES="
	adler2@2.0.0
	aho-corasick@1.1.3
	anstream@0.6.15
	anstyle-parse@0.2.5
	anstyle-query@1.1.1
	anstyle-wincon@3.0.4
	anstyle@1.0.8
	anyhow@1.0.90
	autocfg@1.4.0
	bstr@1.10.0
	byteorder@1.5.0
	cc@1.1.31
	cfg-if@1.0.0
	clap@4.5.20
	clap_builder@4.5.20
	clap_derive@4.5.18
	clap_lex@0.7.2
	colorchoice@1.0.2
	crc32fast@1.4.2
	crossbeam-deque@0.8.5
	crossbeam-epoch@0.9.18
	crossbeam-utils@0.8.20
	difference@2.0.0
	either@1.13.0
	env_filter@0.1.2
	env_logger@0.11.5
	flate2@1.0.34
	globset@0.4.15
	heck@0.5.0
	humantime@2.1.0
	ignore@0.4.23
	is_terminal_polyfill@1.70.1
	itoa@1.0.11
	jobserver@0.1.32
	lazy_static@1.5.0
	libc@0.2.161
	log@0.4.22
	memchr@2.7.4
	miniz_oxide@0.8.0
	num-traits@0.2.19
	paste@1.0.15
	pkg-config@0.3.31
	proc-macro2@1.0.88
	quote@1.0.37
	rayon-core@1.12.1
	rayon@1.10.0
	regex-automata@0.4.8
	regex-syntax@0.8.5
	regex@1.11.0
	rmp-serde@1.3.0
	rmp@0.8.14
	ryu@1.0.18
	same-file@1.0.6
	serde@1.0.210
	serde_derive@1.0.210
	serde_json@1.0.132
	shlex@1.3.0
	strsim@0.11.1
	syn@2.0.82
	tinyvec@1.8.0
	tinyvec_macros@0.1.1
	unicode-ident@1.0.13
	unicode-normalization@0.1.24
	utf8parse@0.2.2
	walkdir@2.5.0
	winapi-util@0.1.9
	windows-sys@0.52.0
	windows-sys@0.59.0
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.52.6
	zstd-safe@7.2.1
	zstd-sys@2.0.13+zstd.1.5.6
	zstd@0.13.2
"

inherit cargo

MY_PN="askalono"
MY_P="${MY_PN}-${PV}"

# updated SPDX license list data; generated with:
# $ git clone https://github.com/spdx/license-list-data.git spdx-license-list -b v3.22 --depth 1
# $ askalono cache load-spdx spdx-license-list/json/details
# $ mv askalono-cache.bin.zstd askalono-cache-3.22.bin.zstd
LICENSE_SOURCE="askalono-cache-3.22.bin.zstd"

DESCRIPTION="A tool to detect the contents of license files"
HOMEPAGE="https://crates.io/crates/askalono-cli"
SRC_URI="
	https://github.com/jpeddicord/${MY_PN}/archive/refs/tags/${PV}.tar.gz -> ${MY_P}.gh.tar.gz
	https://linuxmonk.ch/packages/distfiles/${LICENSE_SOURCE}
	${CARGO_CRATE_URIS}
"
S="${WORKDIR}/${MY_P}/cli"

LICENSE="Apache-2.0"
# Dependent crate licenses
LICENSE+="
	MIT Unicode-DFS-2016
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"
KEYWORDS="~amd64"

src_prepare() {
	default
	# update bundled SPDX license list data
	cp "${DISTDIR}/${LICENSE_SOURCE}" embedded-cache.bin.zstd
}

src_install() {
	cargo_src_install
	dodoc *.md
}
